/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiGenerationStats {
  'incentiveLevel' : { 'free' : null } |
    { 'paid' : null },
  'remainingMillis' : bigint,
  'totalAllowanceMillis' : bigint,
  'usedMillis' : bigint,
}
export type AiGenerationTier = {
    'freeTier' : { 'usedDurationMillis' : bigint }
  } |
  { 'paidTier' : { 'usedDurationMillis' : bigint } };
export interface Channel {
  'channelName' : string,
  'owner' : Principal,
  'createdDate' : Time,
  'description' : string,
}
export interface ChatMessage {
  'isAI' : boolean,
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Comment {
  'id' : CommentId,
  'content' : string,
  'hidden' : boolean,
  'user' : User,
  'pinned' : boolean,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export interface Playlist {
  'id' : PlaylistId,
  'owner' : User,
  'name' : string,
  'createdDate' : Time,
  'isPrivate' : boolean,
  'videoIds' : Array<VideoId>,
}
export type PlaylistId = bigint;
export interface SavedImage {
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionStatus = { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type User = Principal;
export interface UserProfile {
  'name' : string,
  'subscriptionStatus' : SubscriptionStatus,
  'aiGenerationTier' : [] | [AiGenerationTier],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'likeCount' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'tags' : Array<string>,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'viewCount' : bigint,
  'uploader' : User,
  'uploadDate' : Time,
}
export type VideoId = bigint;
export interface VideoMetadata {
  'id' : VideoId,
  'title' : string,
  'likeCount' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'tags' : Array<string>,
  'description' : string,
  'viewCount' : bigint,
  'uploader' : User,
  'uploadDate' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[VideoId, string], CommentId>,
  'addVideoToPlaylist' : ActorMethod<[PlaylistId, VideoId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAiStudioCheckoutSession' : ActorMethod<[string, string], string>,
  'createChannel' : ActorMethod<[string, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPlaylist' : ActorMethod<[string, boolean], PlaylistId>,
  'createVideoPurchaseCheckoutSession' : ActorMethod<
    [VideoId, string, string],
    string
  >,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteSavedImage' : ActorMethod<[string], undefined>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[Principal], [] | [Channel]>,
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  'getGenerationStats' : ActorMethod<[], AiGenerationStats>,
  'getLatestMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getOlderMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'getPlaylist' : ActorMethod<[PlaylistId], [] | [Playlist]>,
  'getPublicPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getSavedImages' : ActorMethod<[], Array<SavedImage>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserPlaylists' : ActorMethod<[User], Array<Playlist>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideos' : ActorMethod<[User], Array<Video>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'getVideoMetadata' : ActorMethod<[VideoId], [] | [VideoMetadata]>,
  'getViewCount' : ActorMethod<[VideoId], bigint>,
  'hasVideoPurchaseEntitlement' : ActorMethod<[bigint], boolean>,
  'hideComment' : ActorMethod<[CommentId], undefined>,
  'incrementViewCount' : ActorMethod<[VideoId], undefined>,
  'isAiStudioPurchased' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'pinComment' : ActorMethod<[CommentId], undefined>,
  'postMessage' : ActorMethod<[string, string], undefined>,
  'removeVideoFromPlaylist' : ActorMethod<[PlaylistId, VideoId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveImage' : ActorMethod<[SavedImage], undefined>,
  'searchPlaylists' : ActorMethod<[string], Array<Playlist>>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'setPayoutDestination' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unhideComment' : ActorMethod<[CommentId], undefined>,
  'unpinComment' : ActorMethod<[CommentId], undefined>,
  'updateChannelAbout' : ActorMethod<[string, string], undefined>,
  'updateGenerationStats' : ActorMethod<[bigint], undefined>,
  'updateTags' : ActorMethod<[VideoId, Array<string>], undefined>,
  'updateThumbnail' : ActorMethod<[VideoId, ExternalBlob], undefined>,
  'updateVideoMetadata' : ActorMethod<[VideoId, string, string], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, ExternalBlob, [] | [ExternalBlob], Array<string>],
    undefined
  >,
  'verifyAndGrantAiAccess' : ActorMethod<[string], undefined>,
  'verifyAndGrantVideoPurchase' : ActorMethod<[string, VideoId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];