/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const CommentId = IDL.Nat;
export const PlaylistId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const User = IDL.Principal;
export const Time = IDL.Int;
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'viewCount' : IDL.Nat,
  'uploader' : User,
  'uploadDate' : Time,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const AiGenerationTier = IDL.Variant({
  'freeTier' : IDL.Record({ 'usedDurationMillis' : IDL.Nat }),
  'paidTier' : IDL.Record({ 'usedDurationMillis' : IDL.Nat }),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
  'aiGenerationTier' : IDL.Opt(AiGenerationTier),
});
export const Channel = IDL.Record({
  'channelName' : IDL.Text,
  'owner' : IDL.Principal,
  'createdDate' : Time,
  'description' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'hidden' : IDL.Bool,
  'user' : User,
  'pinned' : IDL.Bool,
  'timestamp' : Time,
  'videoId' : VideoId,
});
export const AiGenerationStats = IDL.Record({
  'incentiveLevel' : IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
  'remainingMillis' : IDL.Nat,
  'totalAllowanceMillis' : IDL.Nat,
  'usedMillis' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'isAI' : IDL.Bool,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Playlist = IDL.Record({
  'id' : PlaylistId,
  'owner' : User,
  'name' : IDL.Text,
  'createdDate' : Time,
  'isPrivate' : IDL.Bool,
  'videoIds' : IDL.Vec(VideoId),
});
export const SavedImage = IDL.Record({
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VideoMetadata = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'uploader' : User,
  'uploadDate' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
  'addVideoToPlaylist' : IDL.Func([PlaylistId, VideoId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAiStudioCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPlaylist' : IDL.Func([IDL.Text, IDL.Bool], [PlaylistId], []),
  'createVideoPurchaseCheckoutSession' : IDL.Func(
      [VideoId, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deleteSavedImage' : IDL.Func([IDL.Text], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([IDL.Principal], [IDL.Opt(Channel)], ['query']),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getGenerationStats' : IDL.Func([], [AiGenerationStats], ['query']),
  'getLatestMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getOlderMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(Playlist)], ['query']),
  'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getSavedImages' : IDL.Func([], [IDL.Vec(SavedImage)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserPlaylists' : IDL.Func([User], [IDL.Vec(Playlist)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([User], [IDL.Vec(Video)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'getVideoMetadata' : IDL.Func([VideoId], [IDL.Opt(VideoMetadata)], ['query']),
  'getViewCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
  'hasVideoPurchaseEntitlement' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'hideComment' : IDL.Func([CommentId], [], []),
  'incrementViewCount' : IDL.Func([VideoId], [], []),
  'isAiStudioPurchased' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'pinComment' : IDL.Func([CommentId], [], []),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeVideoFromPlaylist' : IDL.Func([PlaylistId, VideoId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveImage' : IDL.Func([SavedImage], [], []),
  'searchPlaylists' : IDL.Func([IDL.Text], [IDL.Vec(Playlist)], ['query']),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'setPayoutDestination' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unhideComment' : IDL.Func([CommentId], [], []),
  'unpinComment' : IDL.Func([CommentId], [], []),
  'updateChannelAbout' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateGenerationStats' : IDL.Func([IDL.Nat], [], []),
  'updateTags' : IDL.Func([VideoId, IDL.Vec(IDL.Text)], [], []),
  'updateThumbnail' : IDL.Func([VideoId, ExternalBlob], [], []),
  'updateVideoMetadata' : IDL.Func([VideoId, IDL.Text, IDL.Text], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'verifyAndGrantAiAccess' : IDL.Func([IDL.Text], [], []),
  'verifyAndGrantVideoPurchase' : IDL.Func([IDL.Text, VideoId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const CommentId = IDL.Nat;
  const PlaylistId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const User = IDL.Principal;
  const Time = IDL.Int;
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'viewCount' : IDL.Nat,
    'uploader' : User,
    'uploadDate' : Time,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const AiGenerationTier = IDL.Variant({
    'freeTier' : IDL.Record({ 'usedDurationMillis' : IDL.Nat }),
    'paidTier' : IDL.Record({ 'usedDurationMillis' : IDL.Nat }),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
    'aiGenerationTier' : IDL.Opt(AiGenerationTier),
  });
  const Channel = IDL.Record({
    'channelName' : IDL.Text,
    'owner' : IDL.Principal,
    'createdDate' : Time,
    'description' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'hidden' : IDL.Bool,
    'user' : User,
    'pinned' : IDL.Bool,
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  const AiGenerationStats = IDL.Record({
    'incentiveLevel' : IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null }),
    'remainingMillis' : IDL.Nat,
    'totalAllowanceMillis' : IDL.Nat,
    'usedMillis' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'isAI' : IDL.Bool,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Playlist = IDL.Record({
    'id' : PlaylistId,
    'owner' : User,
    'name' : IDL.Text,
    'createdDate' : Time,
    'isPrivate' : IDL.Bool,
    'videoIds' : IDL.Vec(VideoId),
  });
  const SavedImage = IDL.Record({
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VideoMetadata = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'uploader' : User,
    'uploadDate' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
    'addVideoToPlaylist' : IDL.Func([PlaylistId, VideoId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAiStudioCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPlaylist' : IDL.Func([IDL.Text, IDL.Bool], [PlaylistId], []),
    'createVideoPurchaseCheckoutSession' : IDL.Func(
        [VideoId, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deleteSavedImage' : IDL.Func([IDL.Text], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([IDL.Principal], [IDL.Opt(Channel)], ['query']),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getGenerationStats' : IDL.Func([], [AiGenerationStats], ['query']),
    'getLatestMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getOlderMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(Playlist)], ['query']),
    'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getSavedImages' : IDL.Func([], [IDL.Vec(SavedImage)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserPlaylists' : IDL.Func([User], [IDL.Vec(Playlist)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([User], [IDL.Vec(Video)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'getVideoMetadata' : IDL.Func(
        [VideoId],
        [IDL.Opt(VideoMetadata)],
        ['query'],
      ),
    'getViewCount' : IDL.Func([VideoId], [IDL.Nat], ['query']),
    'hasVideoPurchaseEntitlement' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'hideComment' : IDL.Func([CommentId], [], []),
    'incrementViewCount' : IDL.Func([VideoId], [], []),
    'isAiStudioPurchased' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'pinComment' : IDL.Func([CommentId], [], []),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeVideoFromPlaylist' : IDL.Func([PlaylistId, VideoId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveImage' : IDL.Func([SavedImage], [], []),
    'searchPlaylists' : IDL.Func([IDL.Text], [IDL.Vec(Playlist)], ['query']),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'setPayoutDestination' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unhideComment' : IDL.Func([CommentId], [], []),
    'unpinComment' : IDL.Func([CommentId], [], []),
    'updateChannelAbout' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateGenerationStats' : IDL.Func([IDL.Nat], [], []),
    'updateTags' : IDL.Func([VideoId, IDL.Vec(IDL.Text)], [], []),
    'updateThumbnail' : IDL.Func([VideoId, ExternalBlob], [], []),
    'updateVideoMetadata' : IDL.Func([VideoId, IDL.Text, IDL.Text], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'verifyAndGrantAiAccess' : IDL.Func([IDL.Text], [], []),
    'verifyAndGrantVideoPurchase' : IDL.Func([IDL.Text, VideoId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };