/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    tags: Array<string>;
    description: string;
    videoBlob: ExternalBlob;
    viewCount: bigint;
    uploader: User;
    uploadDate: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AiGenerationStats {
    incentiveLevel: Variant_free_paid;
    remainingMillis: bigint;
    totalAllowanceMillis: bigint;
    usedMillis: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type PlaylistId = bigint;
export type VideoId = bigint;
export interface ChatMessage {
    isAI: boolean;
    sender: string;
    message: string;
    timestamp: Time;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    content: string;
    hidden: boolean;
    user: User;
    pinned: boolean;
    timestamp: Time;
    videoId: VideoId;
}
export type User = Principal;
export interface Playlist {
    id: PlaylistId;
    owner: User;
    name: string;
    createdDate: Time;
    isPrivate: boolean;
    videoIds: Array<VideoId>;
}
export interface Channel {
    channelName: string;
    owner: Principal;
    createdDate: Time;
    description: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type AiGenerationTier = {
    __kind__: "freeTier";
    freeTier: {
        usedDurationMillis: bigint;
    };
} | {
    __kind__: "paidTier";
    paidTier: {
        usedDurationMillis: bigint;
    };
};
export interface SavedImage {
    title: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
}
export interface VideoMetadata {
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    tags: Array<string>;
    description: string;
    viewCount: bigint;
    uploader: User;
    uploadDate: Time;
}
export interface UserProfile {
    name: string;
    subscriptionStatus: SubscriptionStatus;
    aiGenerationTier?: AiGenerationTier;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SubscriptionStatus {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_free_paid {
    free = "free",
    paid = "paid"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(videoId: VideoId, content: string): Promise<CommentId>;
    addVideoToPlaylist(playlistId: PlaylistId, videoId: VideoId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAiStudioCheckoutSession(successUrl: string, cancelUrl: string): Promise<string>;
    createChannel(channelName: string, description: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPlaylist(name: string, isPrivate: boolean): Promise<PlaylistId>;
    createVideoPurchaseCheckoutSession(videoId: VideoId, successUrl: string, cancelUrl: string): Promise<string>;
    deleteComment(commentId: CommentId): Promise<void>;
    deleteSavedImage(imageUrl: string): Promise<void>;
    getAllVideos(): Promise<Array<Video>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(owner: Principal): Promise<Channel | null>;
    getComments(videoId: VideoId): Promise<Array<Comment>>;
    getGenerationStats(): Promise<AiGenerationStats>;
    getLatestMessages(count: bigint): Promise<Array<ChatMessage>>;
    getOlderMessages(offset: bigint, count: bigint): Promise<Array<ChatMessage>>;
    getPlaylist(playlistId: PlaylistId): Promise<Playlist | null>;
    getPublicPlaylists(): Promise<Array<Playlist>>;
    getSavedImages(): Promise<Array<SavedImage>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserPlaylists(user: User): Promise<Array<Playlist>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserVideos(user: User): Promise<Array<Video>>;
    getVideo(videoId: VideoId): Promise<Video | null>;
    getVideoMetadata(videoId: VideoId): Promise<VideoMetadata | null>;
    getViewCount(_videoId: VideoId): Promise<bigint>;
    hasVideoPurchaseEntitlement(videoId: bigint): Promise<boolean>;
    hideComment(commentId: CommentId): Promise<void>;
    incrementViewCount(videoId: VideoId): Promise<void>;
    isAiStudioPurchased(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeVideo(videoId: VideoId): Promise<void>;
    pinComment(commentId: CommentId): Promise<void>;
    postMessage(sender: string, message: string): Promise<void>;
    removeVideoFromPlaylist(playlistId: PlaylistId, videoId: VideoId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveImage(image: SavedImage): Promise<void>;
    searchPlaylists(searchTerm: string): Promise<Array<Playlist>>;
    searchVideos(searchTerm: string): Promise<Array<Video>>;
    setPayoutDestination(destinationId: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unhideComment(commentId: CommentId): Promise<void>;
    unpinComment(commentId: CommentId): Promise<void>;
    updateChannelAbout(channelName: string, newAbout: string): Promise<void>;
    updateGenerationStats(durationMillis: bigint): Promise<void>;
    updateTags(videoId: VideoId, newTags: Array<string>): Promise<void>;
    updateThumbnail(videoId: VideoId, newThumbnail: ExternalBlob): Promise<void>;
    updateVideoMetadata(videoId: VideoId, newTitle: string, newDescription: string): Promise<void>;
    uploadVideo(title: string, description: string, videoBlob: ExternalBlob, thumbnail: ExternalBlob | null, tags: Array<string>): Promise<void>;
    verifyAndGrantAiAccess(sessionId: string): Promise<void>;
    verifyAndGrantVideoPurchase(sessionId: string, videoId: VideoId): Promise<void>;
}
import type { AiGenerationStats as _AiGenerationStats, AiGenerationTier as _AiGenerationTier, Channel as _Channel, ExternalBlob as _ExternalBlob, Playlist as _Playlist, StripeSessionStatus as _StripeSessionStatus, SubscriptionStatus as _SubscriptionStatus, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, VideoMetadata as _VideoMetadata, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: VideoId, arg1: string): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addVideoToPlaylist(arg0: PlaylistId, arg1: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoToPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoToPlaylist(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAiStudioCheckoutSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAiStudioCheckoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAiStudioCheckoutSession(arg0, arg1);
            return result;
        }
    }
    async createChannel(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPlaylist(arg0: string, arg1: boolean): Promise<PlaylistId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0, arg1);
            return result;
        }
    }
    async createVideoPurchaseCheckoutSession(arg0: VideoId, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoPurchaseCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoPurchaseCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteSavedImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavedImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavedImage(arg0);
            return result;
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: Principal): Promise<Channel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: VideoId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getGenerationStats(): Promise<AiGenerationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenerationStats();
                return from_candid_AiGenerationStats_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenerationStats();
            return from_candid_AiGenerationStats_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestMessages(arg0);
            return result;
        }
    }
    async getOlderMessages(arg0: bigint, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOlderMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOlderMessages(arg0, arg1);
            return result;
        }
    }
    async getPlaylist(arg0: PlaylistId): Promise<Playlist | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylist(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylist(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPlaylists();
            return result;
        }
    }
    async getSavedImages(): Promise<Array<SavedImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedImages();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPlaylists(arg0: User): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPlaylists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPlaylists(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserVideos(arg0: User): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserVideos(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserVideos(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoMetadata(arg0: VideoId): Promise<VideoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoMetadata(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoMetadata(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getViewCount(arg0: VideoId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViewCount(arg0);
            return result;
        }
    }
    async hasVideoPurchaseEntitlement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasVideoPurchaseEntitlement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasVideoPurchaseEntitlement(arg0);
            return result;
        }
    }
    async hideComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hideComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hideComment(arg0);
            return result;
        }
    }
    async incrementViewCount(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async isAiStudioPurchased(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAiStudioPurchased();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAiStudioPurchased();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeVideo(arg0);
            return result;
        }
    }
    async pinComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinComment(arg0);
            return result;
        }
    }
    async postMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1);
            return result;
        }
    }
    async removeVideoFromPlaylist(arg0: PlaylistId, arg1: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVideoFromPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVideoFromPlaylist(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveImage(arg0: SavedImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveImage(arg0);
            return result;
        }
    }
    async searchPlaylists(arg0: string): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlaylists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlaylists(arg0);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPayoutDestination(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPayoutDestination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPayoutDestination(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unhideComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unhideComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unhideComment(arg0);
            return result;
        }
    }
    async unpinComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinComment(arg0);
            return result;
        }
    }
    async updateChannelAbout(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannelAbout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannelAbout(arg0, arg1);
            return result;
        }
    }
    async updateGenerationStats(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGenerationStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGenerationStats(arg0);
            return result;
        }
    }
    async updateTags(arg0: VideoId, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTags(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTags(arg0, arg1);
            return result;
        }
    }
    async updateThumbnail(arg0: VideoId, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateThumbnail(arg0, await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateThumbnail(arg0, await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVideoMetadata(arg0: VideoId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoMetadata(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoMetadata(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadVideo(arg0: string, arg1: string, arg2: ExternalBlob, arg3: ExternalBlob | null, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, arg1, await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, arg1, await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async verifyAndGrantAiAccess(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndGrantAiAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndGrantAiAccess(arg0);
            return result;
        }
    }
    async verifyAndGrantVideoPurchase(arg0: string, arg1: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndGrantVideoPurchase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndGrantVideoPurchase(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AiGenerationStats_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiGenerationStats): AiGenerationStats {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_AiGenerationTier_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiGenerationTier): AiGenerationTier {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StripeSessionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoMetadata_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): Promise<VideoMetadata> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AiGenerationTier]): AiGenerationTier | null {
    return value.length === 0 ? null : from_candid_AiGenerationTier_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Channel]): Channel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Playlist]): Playlist | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoMetadata]): Promise<VideoMetadata | null> {
    return value.length === 0 ? null : await from_candid_VideoMetadata_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    likeCount: bigint;
    thumbnail: [] | [_ExternalBlob];
    tags: Array<string>;
    description: string;
    videoBlob: _ExternalBlob;
    viewCount: bigint;
    uploader: _User;
    uploadDate: _Time;
}): Promise<{
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    tags: Array<string>;
    description: string;
    videoBlob: ExternalBlob;
    viewCount: bigint;
    uploader: User;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.thumbnail)),
        tags: value.tags,
        description: value.description,
        videoBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.videoBlob),
        viewCount: value.viewCount,
        uploader: value.uploader,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    subscriptionStatus: _SubscriptionStatus;
    aiGenerationTier: [] | [_AiGenerationTier];
}): {
    name: string;
    subscriptionStatus: SubscriptionStatus;
    aiGenerationTier?: AiGenerationTier;
} {
    return {
        name: value.name,
        subscriptionStatus: from_candid_SubscriptionStatus_n18(_uploadFile, _downloadFile, value.subscriptionStatus),
        aiGenerationTier: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.aiGenerationTier))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incentiveLevel: {
        free: null;
    } | {
        paid: null;
    };
    remainingMillis: bigint;
    totalAllowanceMillis: bigint;
    usedMillis: bigint;
}): {
    incentiveLevel: Variant_free_paid;
    remainingMillis: bigint;
    totalAllowanceMillis: bigint;
    usedMillis: bigint;
} {
    return {
        incentiveLevel: from_candid_variant_n28(_uploadFile, _downloadFile, value.incentiveLevel),
        remainingMillis: value.remainingMillis,
        totalAllowanceMillis: value.totalAllowanceMillis,
        usedMillis: value.usedMillis
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    likeCount: bigint;
    thumbnail: [] | [_ExternalBlob];
    tags: Array<string>;
    description: string;
    viewCount: bigint;
    uploader: _User;
    uploadDate: _Time;
}): Promise<{
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnail?: ExternalBlob;
    tags: Array<string>;
    description: string;
    viewCount: bigint;
    uploader: User;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.thumbnail)),
        tags: value.tags,
        description: value.description,
        viewCount: value.viewCount,
        uploader: value.uploader,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeTier: {
        usedDurationMillis: bigint;
    };
} | {
    paidTier: {
        usedDurationMillis: bigint;
    };
}): {
    __kind__: "freeTier";
    freeTier: {
        usedDurationMillis: bigint;
    };
} | {
    __kind__: "paidTier";
    paidTier: {
        usedDurationMillis: bigint;
    };
} {
    return "freeTier" in value ? {
        __kind__: "freeTier",
        freeTier: value.freeTier
    } : "paidTier" in value ? {
        __kind__: "paidTier",
        paidTier: value.paidTier
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    paid: null;
}): Variant_free_paid {
    return "free" in value ? Variant_free_paid.free : "paid" in value ? Variant_free_paid.paid : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n32(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n11(_uploadFile, _downloadFile, x)));
}
function to_candid_AiGenerationTier_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AiGenerationTier): _AiGenerationTier {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SubscriptionStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n44(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    subscriptionStatus: SubscriptionStatus;
    aiGenerationTier?: AiGenerationTier;
}): {
    name: string;
    subscriptionStatus: _SubscriptionStatus;
    aiGenerationTier: [] | [_AiGenerationTier];
} {
    return {
        name: value.name,
        subscriptionStatus: to_candid_SubscriptionStatus_n40(_uploadFile, _downloadFile, value.subscriptionStatus),
        aiGenerationTier: value.aiGenerationTier ? candid_some(to_candid_AiGenerationTier_n42(_uploadFile, _downloadFile, value.aiGenerationTier)) : candid_none()
    };
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "freeTier";
    freeTier: {
        usedDurationMillis: bigint;
    };
} | {
    __kind__: "paidTier";
    paidTier: {
        usedDurationMillis: bigint;
    };
}): {
    freeTier: {
        usedDurationMillis: bigint;
    };
} | {
    paidTier: {
        usedDurationMillis: bigint;
    };
} {
    return value.__kind__ === "freeTier" ? {
        freeTier: value.freeTier
    } : value.__kind__ === "paidTier" ? {
        paidTier: value.paidTier
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
